// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingApi.DBContexts;

namespace TicketingApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210727033940_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("TicketingApi.Models.v1.Misc.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("desc");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_Apps");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_name");

                    b.ToTable("apps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Integrated Advertising System",
                            Logo = "Apps/Sysad.jpg",
                            Name = "SysAd"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "",
                            Name = "App2"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "",
                            Name = "App3"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "",
                            Name = "APP4"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Misc.KBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppId")
                        .HasColumnType("int")
                        .HasColumnName("app_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_KBase");

                    b.ToTable("kbases");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Misc.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_type");

                    b.Property<int>("RelId")
                        .HasColumnType("int")
                        .HasColumnName("rel_id");

                    b.Property<string>("RelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("rel_type");

                    b.Property<int?>("TicketDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketsId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Media");

                    b.HasIndex("TicketDetailsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "Tickets/atc1.jpg",
                            FileType = ".pf",
                            RelId = 1,
                            RelType = "T"
                        },
                        new
                        {
                            Id = 2,
                            FileName = "Tickets/atc2.pdf",
                            FileType = ".pdf",
                            RelId = 1,
                            RelType = "T"
                        },
                        new
                        {
                            Id = 3,
                            FileName = "TicketDetails/atc3.jpeg",
                            FileType = ".jpg",
                            RelId = 1,
                            RelType = "TD"
                        },
                        new
                        {
                            Id = 4,
                            FileName = "TicketsDetails/atc4.xls",
                            FileType = ".xls",
                            RelId = 1,
                            RelType = "TD"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Misc.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppId")
                        .HasColumnType("int")
                        .HasColumnName("app_id");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("desc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_Modules");

                    b.HasIndex("AppId");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_name");

                    b.ToTable("modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppId = 1,
                            Desc = "",
                            Name = "Media"
                        },
                        new
                        {
                            Id = 2,
                            AppId = 1,
                            Desc = "",
                            Name = "Production"
                        },
                        new
                        {
                            Id = 3,
                            AppId = 1,
                            Desc = "",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            AppId = 1,
                            Desc = "",
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("desc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_Stat");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_name");

                    b.ToTable("stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            Desc = "bg-danger",
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Sky",
                            Desc = "bg-info",
                            Name = "Open"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Blue",
                            Desc = "bg-primary",
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Yellow",
                            Desc = "bg-warning",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Green",
                            Desc = "bg-success",
                            Name = "Solve"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Grey",
                            Desc = "bg-dark",
                            Name = "Reject"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppId")
                        .HasColumnType("int")
                        .HasColumnName("app_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rejected_by");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text")
                        .HasColumnName("rejected_reason");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("solved_at");

                    b.Property<string>("SolvedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("solved_by");

                    b.Property<int>("StatId")
                        .HasColumnType("int")
                        .HasColumnName("stat_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ticket_number");

                    b.Property<string>("TicketType")
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ticket_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Ticket");

                    b.HasIndex("AppId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SenderId");

                    b.HasIndex("StatId");

                    b.HasIndex("TicketNumber")
                        .HasDatabaseName("idx_TicketNumber");

                    b.HasIndex("UserId");

                    b.ToTable("tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppId = 1,
                            Comment = "lorem ipsu sdkskadn ksdnksin jdnskjdna jsandjkansdjkansd jndsajkdnajkd kasjndsndoqm dolor shit nyoasdasdaslibay knoper low",
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 651, DateTimeKind.Local).AddTicks(6776),
                            CreatedBy = "daniel@gmail.com",
                            ModuleId = 1,
                            SenderId = 1,
                            StatId = 3,
                            Subject = "Ini Test Subject satu ",
                            TicketNumber = "180620211",
                            TicketType = "E"
                        },
                        new
                        {
                            Id = 2,
                            AppId = 1,
                            Comment = "asdhjkahsdjas jasdjj sjadnajk jasnd jas d asndjka  skjdnaksjdn sshdjkajksdas jashdjkahsjkd oashdasihsjskaslnsk",
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 651, DateTimeKind.Local).AddTicks(8816),
                            CreatedBy = "vickyindiary@yahoo.com",
                            ModuleId = 1,
                            SenderId = 2,
                            StatId = 1,
                            Subject = "Subject for ticket number 2",
                            TicketNumber = "180620212",
                            TicketType = "E"
                        },
                        new
                        {
                            Id = 3,
                            AppId = 1,
                            Comment = "ksknnina  lasklk  klsnklna ksaiopoellss ksdoasjdandanwdwqo sdnskandjasd  jskdnjksanda asndndiqwioqdwq",
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 651, DateTimeKind.Local).AddTicks(8827),
                            CreatedBy = "vickyindiary@yahoo.com",
                            ModuleId = 1,
                            SenderId = 3,
                            StatId = 1,
                            Subject = "Subjecsdskkks ksnkandkasndk t 3",
                            TicketNumber = "180620213",
                            TicketType = "E"
                        },
                        new
                        {
                            Id = 4,
                            AppId = 1,
                            Comment = "ksknnina  lasklk  klsnklna ksaiopoellss ksdoasjdandanwdwqo sdnskandjasd  jskdnjksanda asndndiqwioqdwq",
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 651, DateTimeKind.Local).AddTicks(8830),
                            CreatedBy = "vickyindiary@yahoo.com",
                            ModuleId = 1,
                            StatId = 1,
                            Subject = "BUG SYSAD SAMPLE",
                            TicketNumber = "180620214",
                            TicketType = "I",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.TicketAssign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignType")
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("assign_type");

                    b.Property<DateTime?>("TeamAt")
                        .HasColumnType("datetime")
                        .HasColumnName("team_at");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UserAt")
                        .HasColumnType("datetime")
                        .HasColumnName("user_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<bool>("Viewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("viewed");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("viewed_at");

                    b.HasKey("Id")
                        .HasName("PK_Ticket_assign");

                    b.HasIndex("TeamId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("ticket_assigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignType = "M",
                            TicketId = 1,
                            UserAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(2522),
                            UserId = 2,
                            Viewed = true,
                            ViewedAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(2535)
                        },
                        new
                        {
                            Id = 2,
                            AssignType = "T",
                            TeamAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(4151),
                            TeamId = 1,
                            TicketId = 1,
                            UserId = 4,
                            Viewed = true,
                            ViewedAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(4159)
                        },
                        new
                        {
                            Id = 3,
                            AssignType = "U",
                            TicketId = 1,
                            UserAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(5632),
                            UserId = 6,
                            Viewed = true,
                            ViewedAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(5639)
                        },
                        new
                        {
                            Id = 4,
                            AssignType = "M",
                            TicketId = 2,
                            UserAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(5643),
                            UserId = 2,
                            Viewed = false
                        },
                        new
                        {
                            Id = 5,
                            AssignType = "M",
                            TicketId = 3,
                            UserAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(6863),
                            UserId = 2,
                            Viewed = false
                        },
                        new
                        {
                            Id = 6,
                            AssignType = "M",
                            TicketId = 4,
                            UserAt = new DateTime(2021, 7, 27, 10, 39, 38, 661, DateTimeKind.Local).AddTicks(6871),
                            UserId = 3,
                            Viewed = false
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.TicketDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("flag");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Ticket_details");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("ticket_details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "lorem ipsum dolor shit nyolibay kksdj nknop ksiola knoper low",
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 660, DateTimeKind.Local).AddTicks(751),
                            TicketId = 1,
                            UpdatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 660, DateTimeKind.Local).AddTicks(772),
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Comment = "asdhjkahsdjas jasshdjkajksdas jashdjkahsjkd oashdasihsjskaslnsk",
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 660, DateTimeKind.Local).AddTicks(2642),
                            TicketId = 1,
                            UpdatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 660, DateTimeKind.Local).AddTicks(2651)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "ksknnina  lasklk  klsnklna ksaiopoells;mlauw klnskoiskel aksnkadia mkaskks ",
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 660, DateTimeKind.Local).AddTicks(3888),
                            TicketId = 1,
                            UpdatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 660, DateTimeKind.Local).AddTicks(3896),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("desc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_Depatments");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_name");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "",
                            Name = "Management"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "",
                            Name = "CS"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "",
                            Name = "Programmer"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("desc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_name");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "",
                            Name = "Leader"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Sender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("image");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<bool?>("LoginStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("login_status");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("salt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_Sender");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_sender");

                    b.ToTable("senders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 646, DateTimeKind.Local).AddTicks(1708),
                            Email = "daniel@gmail.com",
                            FirstName = "Daniel",
                            Image = "Users/daniel.jpg",
                            LastName = "Radcliff",
                            Password = "",
                            Salt = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 646, DateTimeKind.Local).AddTicks(1732),
                            Email = "ruppert@gmail.com",
                            FirstName = "Ruppert",
                            Image = "Users/ruppert.jpg",
                            LastName = "Grint",
                            Password = "",
                            Salt = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 646, DateTimeKind.Local).AddTicks(2673),
                            Email = "emma@gmail.com",
                            FirstName = "Emma",
                            Image = "Users/emma.jpg",
                            LastName = "Watson",
                            LoginStatus = true,
                            Password = "64FEFC19C079C63DF213EE78C342DEA22EA24BF68E33A9D5B179A4C6493285235C8E26C2E2081B22161DC3BFCC536D15BC58CB7A8936FFCA103E3F24A0B71438",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("desc");

                    b.Property<int>("LeaderId")
                        .HasColumnType("int")
                        .HasColumnName("leader_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("PK_Teams");

                    b.HasIndex("LeaderId");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_name");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "",
                            LeaderId = 4,
                            Name = "TEAM CAP"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Team_Members");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("team_members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            TeamId = 1,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("image");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("salt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_email");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 639, DateTimeKind.Local).AddTicks(6188),
                            Email = "vicky.indiarto@epsylonhome.com",
                            FirstName = "Vicky",
                            Image = "Users/vicky.jpg",
                            LastName = "Epsylon",
                            Password = "41F0070B1CAD67A1852B5F6F0E7D4A8F57ED768975C0D691B49AFCFC033F6A23A497EC68138C20573BDC162DC87086EC08748DEB18D87154B2AB94B92F1E7446",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 639, DateTimeKind.Local).AddTicks(9064),
                            Email = "vickyindiarto@gmail.com",
                            FirstName = "Crish",
                            Image = "Users/crish.jpg",
                            LastName = "Evans",
                            Password = "540A358BA70A8B2026E9737FC4DE40A4C9C48FA70C91BFC1503A09F428453128725CB10A811ACE5316F4432ED6F74BFF4C01707AD14E5FE3E766D4A522D0B40E",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 639, DateTimeKind.Local).AddTicks(9840),
                            Email = "vickynewonline@gmail.com",
                            FirstName = "Mark",
                            Image = "Users/mark.jpg",
                            LastName = "Ruffalo",
                            Password = "053877C492D096F9B5C227EF0D9315E93CE01877EBB2FA0EF9E53E71CDAEAD2531122B5212E0A3A4136CCF94B405B7D4E67EB95292EF63AF6BC77D6030703E7B",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 640, DateTimeKind.Local).AddTicks(577),
                            Email = "vickyindiar@yahoo.com",
                            FirstName = "Robert",
                            Image = "Users/robert.jpg",
                            LastName = "Downy",
                            Password = "307D668DCA51F69CCDCDB6F0A400CB77559F6E5BA4F93BC0D0FF91921F7B16A9B5802A38F1AB6CCA246FD6B559CD702EA37C23F5A4FDD96A4D7B1416C438C0F3",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 640, DateTimeKind.Local).AddTicks(1309),
                            Email = "vickyindiarx@yahoo.com",
                            FirstName = "Tom",
                            Image = "Users/tom.jpg",
                            LastName = "Holan",
                            Password = "7B18DDDFDD9044A7F8E1164D81C9B4E80894FA3041AAF17BE546ACC9948D8210D7B2146257B57C10A0F3EABFACEAEA09C62EA867920DCBA59C2D221ACEE91687",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 640, DateTimeKind.Local).AddTicks(2038),
                            Email = "vickyindiary@yahoo.com",
                            FirstName = "Scarlett",
                            LastName = "Johansson",
                            Password = "7C03E544F57C93339151EB81939899B0AFB6C39A38173FAB1279181BED1F841747AFE2CE057EDDD5A2723775C6D5FAD626AA57FE728283B24C5EEA9C0FB8E637",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 7, 27, 10, 39, 38, 640, DateTimeKind.Local).AddTicks(4428),
                            Email = "vickyindiarz@yahoo.com",
                            FirstName = "Jeremy",
                            LastName = "Renner",
                            Password = "CDC3FD1C80512180A16E4BDB581A05451286A5A4007B50544FE1EAD4392AB830CB2FCAA04BF7156CB96BADAFE2ABFE824C1C9CCF8788366EC57D7FD7513504D2",
                            Salt = "01079031-d15e-4902-a79e-3f4b33963fb1"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.UserDept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_UserDepts");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_userid");

                    b.ToTable("user_depatments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_userid");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            RoleId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            RoleId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            RoleId = 4,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Misc.Media", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Tickets.TicketDetail", "TicketDetails")
                        .WithMany("Medias")
                        .HasForeignKey("TicketDetailsId");

                    b.HasOne("TicketingApi.Models.v1.Tickets.Ticket", "Tickets")
                        .WithMany("Medias")
                        .HasForeignKey("TicketsId");

                    b.Navigation("TicketDetails");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Misc.Module", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Misc.App", null)
                        .WithMany("Modules")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.Ticket", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Misc.App", "Apps")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Misc.Module", "Modules")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Users.Sender", "Senders")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.HasOne("TicketingApi.Models.v1.Tickets.Stat", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Apps");

                    b.Navigation("Modules");

                    b.Navigation("Senders");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.TicketAssign", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Users.Team", "Teams")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("TicketingApi.Models.v1.Tickets.Ticket", null)
                        .WithMany("TicketAssigns")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Users.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.TicketDetail", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Tickets.Ticket", null)
                        .WithMany("TicketDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Users.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Team", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Users.User", "Leader")
                        .WithMany("Teams")
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.TeamMember", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Users.Team", "Teams")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Users.User", "Users")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.UserDept", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Users.Department", "Departments")
                        .WithMany("UserDepts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Users.User", null)
                        .WithMany("UserDepts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.UserRole", b =>
                {
                    b.HasOne("TicketingApi.Models.v1.Users.Role", "Roles")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingApi.Models.v1.Users.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Misc.App", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.Stat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.Ticket", b =>
                {
                    b.Navigation("Medias");

                    b.Navigation("TicketAssigns");

                    b.Navigation("TicketDetails");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Tickets.TicketDetail", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Department", b =>
                {
                    b.Navigation("UserDepts");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.Team", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("TicketingApi.Models.v1.Users.User", b =>
                {
                    b.Navigation("TeamMembers");

                    b.Navigation("Teams");

                    b.Navigation("UserDepts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
